package com.stockflow.product;

import com.stockflow.common.base.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.UUID;

@Entity
@Table(
    name = "products",
    uniqueConstraints = @UniqueConstraint(name = "uq_products_owner_sku", columnNames = {"owner_id", "sku"}),
    indexes = {
        @Index(name = "idx_products_owner_name", columnList = "owner_id, name"),
        @Index(name = "idx_products_owner_sku", columnList = "owner_id, sku")
    }
)
@Getter
@Setter
@NoArgsConstructor
public class Product extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * Owning user - the products table is per-user. The security filter
     * layer ensures a caller can only see rows where owner_id matches their
     * authenticated id.
     */
    @Column(name = "owner_id", nullable = false)
    private UUID ownerId;

    @Column(name = "sku", length = 64, nullable = false)
    private String sku;

    @Column(name = "name", length = 255, nullable = false)
    private String name;

    @Column(name = "description", length = 2000)
    private String description;

    /**
     * Stored as DECIMAL(19,2) so we never lose pennies to float drift.
     */
    @Column(name = "unit_price", nullable = false, precision = 19, scale = 2)
    private BigDecimal unitPrice;

    @Column(name = "quantity_on_hand", nullable = false)
    private int quantityOnHand;

    @Override
    public Object entityId() {
        return id;
    }

    /**
     * Convenience typed accessor - the canonical {@code getId()} is
     * generated by Lombok on the {@code id} field. This override exists
     * only to satisfy {@link BaseEntity#entityId()}.
     */
}
