package com.stockflow.invoice;

import com.stockflow.common.base.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.math.BigDecimal;
import java.util.UUID;

@Entity
@Table(
    name = "invoice_items",
    indexes = {
        @Index(name = "idx_invoice_items_invoice", columnList = "invoice_id"),
        @Index(name = "idx_invoice_items_product", columnList = "product_id")
    }
)
@Getter
@Setter
@NoArgsConstructor
@ToString(exclude = "invoice")
public class InvoiceItem extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @ManyToOne(optional = false)
    @JoinColumn(name = "invoice_id", nullable = false)
    private Invoice invoice;

    /**
     * Reference back to the product. Used for stock guards and to detect
     * references when deleting a product. Not strictly required for display
     * since we snapshot name and unitPrice.
     */
    @Column(name = "product_id", nullable = false)
    private UUID productId;

    /**
     * Snapshot of the product name at the time the line item was created.
     */
    @Column(name = "product_name_snapshot", length = 255, nullable = false)
    private String productNameSnapshot;

    /**
     * Snapshot of the unit price at the time the line item was created.
     * Stored as DECIMAL so we never round-trip through double.
     */
    @Column(name = "unit_price_snapshot", nullable = false, precision = 19, scale = 2)
    private BigDecimal unitPriceSnapshot;

    @Column(name = "quantity", nullable = false)
    private int quantity;

    @Column(name = "line_total", nullable = false, precision = 19, scale = 2)
    private BigDecimal lineTotal;

    @Column(name = "position", nullable = false)
    private int position;

    @Override
    public Object entityId() {
        return id;
    }

    /**
     * Convenience typed accessor - the canonical {@code getId()} is
     * generated by Lombok on the {@code id} field. This override exists
     * only to satisfy {@link BaseEntity#entityId()}.
     */
}
