package com.stockflow.invoice;

import com.stockflow.common.base.BaseEntity;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OrderBy;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

@Entity
@Table(
    name = "invoices",
    uniqueConstraints = @UniqueConstraint(name = "uq_invoices_owner_number", columnNames = {"owner_id", "invoice_number"}),
    indexes = {
        @Index(name = "idx_invoices_owner_status", columnList = "owner_id, status"),
        @Index(name = "idx_invoices_owner_issue_date", columnList = "owner_id, issue_date")
    }
)
@Getter
@Setter
@NoArgsConstructor
public class Invoice extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "owner_id", nullable = false)
    private UUID ownerId;

    /**
     * Human-friendly, auto-generated number such as {@code INV-2026-0001}.
     * Unique per owner, not globally - two users can independently number
     * their invoices from one.
     */
    @Column(name = "invoice_number", length = 32, nullable = false)
    private String invoiceNumber;

    @Column(name = "customer_name", length = 255, nullable = false)
    private String customerName;

    @Column(name = "issue_date", nullable = false)
    private LocalDate issueDate;

    @Column(name = "due_date")
    private LocalDate dueDate;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 16, nullable = false)
    private InvoiceStatus status = InvoiceStatus.DRAFT;

    @Column(name = "notes", length = 2000)
    private String notes;

    @Column(name = "subtotal", nullable = false, precision = 19, scale = 2)
    private BigDecimal subtotal = BigDecimal.ZERO;

    @Column(name = "tax_amount", nullable = false, precision = 19, scale = 2)
    private BigDecimal taxAmount = BigDecimal.ZERO;

    @Column(name = "total", nullable = false, precision = 19, scale = 2)
    private BigDecimal total = BigDecimal.ZERO;

    @OneToMany(mappedBy = "invoice", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.EAGER)
    @OrderBy("position ASC")
    private List<InvoiceItem> items = new ArrayList<>();

    public void addItem(InvoiceItem item) {
        item.setInvoice(this);
        item.setPosition(items.size());
        items.add(item);
    }

    @Override
    public Object entityId() {
        return id;
    }

    /**
     * Convenience typed accessor - the canonical {@code getId()} is
     * generated by Lombok on the {@code id} field. This override exists
     * only to satisfy {@link BaseEntity#entityId()}.
     */
}
