package com.stockflow.invoice;

import com.stockflow.common.base.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.UUID;

/**
 * Append-only ledger of stock changes. Each row records a single delta to a
 * product's quantityOnHand, the reason and (when relevant) the invoice that
 * drove it. Provides a full audit trail without needing to mutate history.
 */
@Entity
@Table(
    name = "stock_movements",
    indexes = {
        @Index(name = "idx_stock_movements_owner_product", columnList = "owner_id, product_id"),
        @Index(name = "idx_stock_movements_invoice", columnList = "invoice_id")
    }
)
@Getter
@Setter
@NoArgsConstructor
public class StockMovement extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "owner_id", nullable = false)
    private UUID ownerId;

    @Column(name = "product_id", nullable = false)
    private UUID productId;

    /**
     * Optional - present for invoice-driven movements, null for manual edits.
     */
    @Column(name = "invoice_id")
    private UUID invoiceId;

    @Enumerated(EnumType.STRING)
    @Column(name = "reason", length = 32, nullable = false)
    private StockMovementReason reason;

    /**
     * Signed delta. Negative for an issue, positive for a cancel or
     * adjustment. Stored as INTEGER since on-hand is integer.
     */
    @Column(name = "delta", nullable = false)
    private int delta;

    @Override
    public Object entityId() {
        return id;
    }

    /**
     * Convenience typed accessor - the canonical {@code getId()} is
     * generated by Lombok on the {@code id} field. This override exists
     * only to satisfy {@link BaseEntity#entityId()}.
     */
}
