package com.stockflow.user;

import com.stockflow.common.base.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.UUID;

@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
public class User extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @Column(name = "email", length = 254, nullable = false, unique = true)
    private String email;

    @Column(name = "password_hash", length = 100, nullable = false)
    private String passwordHash;

    @Enumerated(EnumType.STRING)
    @Column(name = "role", length = 32, nullable = false)
    private Role role = Role.STAFF;

    /**
     * Incremented on logout to invalidate every previously issued token.
     * Tokens carry this value as the {@code tv} claim; the auth filter
     * compares them on every request.
     */
    @Column(name = "token_version", nullable = false)
    private long tokenVersion;

    @Override
    public Object entityId() {
        return id;
    }

    /**
     * Convenience typed accessor - the canonical {@code getId()} is
     * generated by Lombok on the {@code id} field. This override exists
     * only to satisfy {@link BaseEntity#entityId()}.
     */
}
